### ISSUE TITLE
Example hangs if Arduino is connected to computer

### ISSUE THREAD

**Issue by danielle-h** [aromajoin/controller-sdk-java#2]
I have an Arduino Leonardo connected to my computer. If the Arduino is connected but there is no program that is currently communicating with it, the example program will hang.

It seems to hang at 
`String serial = SerialReader.query(ASConnection.USB, serialPort);` (USBAController, line 74)
It queries the serial port and waits indefinitely for an answer.

If there is a program that is communicating with the Arduino in parallel to running the example program, the example program runs without issue. 

I am using VSCode 1.63.2 On Windows 10 Pro 10.0.19042.
Arduino board is Arduino Leonardo
java version "1.8.0_321"
Using AromaShooter ASN2A00306

**Comment by danielle-h** [comment]
Additional information:
When running on a Raspberry Pi with an Arduino Due connected, the program doesn't hang but outputs the following error:
```
com.fazecast.jSerialComm.SerialPortTimeoutException: The write operation timed out before all data was written.
        at com.fazecast.jSerialComm.SerialPort$SerialPortOutputStream.write(SerialPort.java:1470)
        at com.fazecast.jSerialComm.SerialPort$SerialPortOutputStream.write(SerialPort.java:1449)
        at com.aromajoin.sdk.jvm.SerialReader.query(SerialReader.java:33)
        at com.aromajoin.sdk.jvm.usb.USBASController.scanAndConnect(USBASController.java:74)
        at com.example.App.main(App.java:22)
```
And the program continues, connecting to the the Aroma Shooter successfully.

**Comment by hanh-aj** [comment]
Hi @danielle-h,

Thanks for reporting the issue.
It seems like the SDK sent UART command too soon when Arduino is not ready.
Could you check if it's related to this link?
https://forum.arduino.cc/t/jserialcomm-serial-communication-with-arduino-uno-fails/589181/11

**Comment by danielle-h** [comment]
I did a few more trials on the Windows computer.
If at the beginning the Arduino is physically connected (with a cable) but no program has opened a connection to the Arduino, then your SDK, in ScanAndConnect, opens a connection to the Arduino and the program runs to completion (so it doesn't look connected to the link).
The second time the program is run (after your program has already opened a connection and closed it) the program will hang.
I assume it's because the Arduino now expects some other input.
But why is your program opening a connection to the Arduino in the first place?
Is there a way to direct the usbController to connect only to the Aroma Shooter? using the serial number or the COM port? I couldn't find a function that does this.

**Comment by danielle-h** [comment]
On Windows, Bluetooth serial link also causes example to hang. Temporary workaround is to go to Device Manager --> Ports and disable any ports called "Standard Serial over Bluetooth Link"

**Comment by Kanghan1003** [comment]
@danielle-h Thank you for these very detailed reports, and I am sorry that they went unanswered for so long.

My name is Kang-Han Kim, and I have taken over maintenance of the AromaShooter SDKs at Aromajoin.

Your three issues (#2, #3, #4) all came from the same place. `scanAndConnect()` opened every serial port on the machine and waited for a reply, with no way to cut a port short — that is what hung on your Arduino, what made discovery fail on the first call, and what dragged the Bluetooth serial device into it.

**v3.1.0** is now on Maven Central (`com.aromajoin.sdk:jvm:3.1.0`) and reworks that path:

- Ports identified as Bluetooth serial ports are skipped and never opened — the "Standard Serial over Bluetooth Link" workaround you found, now done by the SDK itself.
- Each probe runs on a daemon thread that is abandoned after 5 seconds, so a port that never answers can no longer hang the scan or keep the JVM from exiting.
- The probe waits up to 3 seconds for a complete response frame, instead of the fixed 150 ms it used before — that wait was shorter than some devices take to answer, which is why discovery only worked on the second call.
- `connect(AromaShooter, ConnectCallback)` and `disconnect(...)` are implemented and no longer throw. A device found by a scan can be released and re-opened without probing every port again — this is what you were after when you asked whether the controller could be pointed at the Aroma Shooter alone.

Please note 3.1.0 is a breaking release: `Port` is now `AromaChamber`, `diffuse*` is now `shoot*`. The README and CHANGELOG list the full set.

One thing I would appreciate your confirmation on, if you still have the setup: the Bluetooth skip matches on the port description, which is dependable on Windows, but I am not certain it catches the Raspberry Pi's on-board Bluetooth UART (`/dev/ttyAMA0`). If #4 still reproduces there, please say so and I will add an explicit exclusion for it.

Thank you for your patience.

— Kang-Han Kim, Aromajoin

**Comment by danielle-h** [comment]
Thank you for solving these issues! The system we worked on is no longer in use, but we will keep this in mind for next projects.
