### ISSUE TITLE
need to initialize twice to discover Aroma Shooter

### ISSUE THREAD

**Issue by danielle-h** [aromajoin/controller-sdk-java#3]
Using Raspberry pi running Linux 10 (buster).

output of `java -version`:
```
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment (build 11.0.12+7-post-Raspbian-2deb10u1)
OpenJDK Server VM (build 11.0.12+7-post-Raspbian-2deb10u1, mixed mode)
```

```
 private static USBASController initAromajoin() {
    USBASController usbController = new USBASController();
    usbController.scanAndConnect();
    if (!usbController.getConnectedDevices().isEmpty()) {
      for (AromaShooter aromaShooter : usbController.getConnectedDevices()) {
        System.out.println("Connected to AromaShooter: " + aromaShooter.getSerial());
      }
    }
    return usbController;
  }
```

This code never discovers the Aroma shooter in the first time. It always needs to be called twice.

Output first time: (see issue #2)
```
com.fazecast.jSerialComm.SerialPortTimeoutException: The write operation timed out before all data was written.
        at com.fazecast.jSerialComm.SerialPort$SerialPortOutputStream.write(SerialPort.java:1470)
        at com.fazecast.jSerialComm.SerialPort$SerialPortOutputStream.write(SerialPort.java:1449)
        at com.aromajoin.sdk.jvm.SerialReader.query(SerialReader.java:33)
        at com.aromajoin.sdk.jvm.usb.USBASController.scanAndConnect(USBASController.java:74)
        at worg.weizmann.App.initAromajoin(App.java:107)
        at worg.weizmann.App.main(App.java:27)
```

Output second time:
```
com.fazecast.jSerialComm.SerialPortTimeoutException: The write operation timed out before all data was written.
        at com.fazecast.jSerialComm.SerialPort$SerialPortOutputStream.write(SerialPort.java:1470)
        at com.fazecast.jSerialComm.SerialPort$SerialPortOutputStream.write(SerialPort.java:1449)
        at com.aromajoin.sdk.jvm.SerialReader.query(SerialReader.java:33)
        at com.aromajoin.sdk.jvm.usb.USBASController.scanAndConnect(USBASController.java:74)
        at worg.weizmann.App.initAromajoin(App.java:107)
        at worg.weizmann.App.main(App.java:27)
Connected to AromaShooter: ASN2A00306
```

**Comment by Kanghan1003** [comment]
@danielle-h Following up here as well — this was caused by the probe giving up after a fixed 150 ms, which was shorter than the device's response time, so the first `scanAndConnect()` never saw it. v3.1.0 waits up to 3 seconds for a complete frame. Details and the rest of the changes are in #2. Sorry for the long delay, and please let me know if it still needs two calls.

— Kang-Han Kim, Aromajoin

**Comment by danielle-h** [comment]
As I said in #2 , the system is no longer in use. However, we appreciate your effort and hope to use the Aroma Shooter again soon.
